language: c

install:
    - sudo apt-get update -qq
    - sudo apt-get install gcc-multilib

matrix:
  fast_finish: true
branches:
  only:
    - master
    - develop
    - /^release\/.*$/

compiler:
  - gcc
  - clang
script:
  - ./testme.sh --with-cc=$CC ${BUILDOPTIONS}
env:
  - |
    BUILDOPTIONS="--test-vs-mtest=333333"
  - |
    BUILDOPTIONS="--test-vs-mtest=333333 --mtest-real-rand"
  - |
    BUILDOPTIONS="--with-low-mp"
  - |
    BUILDOPTIONS="--with-low-mp --cflags=-DLTM_USE_FASTER_VERSIONS"
  - |
    BUILDOPTIONS="--with-m64 --with-m32 --with-mx32"
  - |
    BUILDOPTIONS="--with-m64 --with-m32 --with-mx32 --cflags=-DLTM_USE_FASTER_VERSIONS"

after_failure:
  - cat test_*.log
  - cat gcc_errors_*.log

notifications:
  irc: "chat.freenode.net#libtom-notifications"
